# Generated by Django 5.1.7 on 2025-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
