# Generated by Django 5.2 on 2025-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0004_shopitem_id_alter_shopitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='allow_uploads',
            field=models.BooleanField(default=False),
        ),
    ]
