# Generated by Django 5.2 on 2025-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0005_admin_allow_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='allow_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='allow_upload_deletions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='mail_send_notifiations',
            field=models.BooleanField(default=False),
        ),
    ]
