# Generated by Django 5.2 on 2025-04-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0006_admin_allow_password_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='mail_send_notifiations',
            new_name='allow_email_notifications',
        ),
    ]
