# Generated by Django 5.2 on 2025-04-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0007_rename_mail_send_notifiations_admin_allow_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='allow_password_change',
        ),
    ]
