# Generated by Django 5.2 on 2025-04-29 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0008_remove_admin_allow_password_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'App Configuation', 'verbose_name_plural': 'App Configuration'},
        ),
        migrations.AddField(
            model_name='admin',
            name='records_per_page',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
