# Generated by Django 5.2.3 on 2025-07-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0009_alter_admin_options_admin_records_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_manager.item'),
        ),
    ]
