# Generated by Django 5.2.3 on 2025-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0010_alter_shopitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
